/**
 * Generate .cursor/commands/orchestrate-prompt.md
 */
export function generateCommands(): string {
  return `# Orchestrate Prompt

## Description
Rewrite a layperson request into a role-aware, repo-contextual, Cursor-native instruction using Context Engineering, Verbalized Sampling, and Self-Adapt.

## Usage
\`\`\`
@orchestrate-prompt "Build a user authentication flow with JWT"
\`\`\`

## Inputs
- **task** (required): The user request to rewrite.
- **mode_flags** (optional):
  - \`vs_enabled\`: Enable Verbalized Sampling (default: true)
  - \`vs_k\`: Number of candidate designs (default: 3)
  - \`self_adapt\`: Enable Self-Adapt loop (default: true)
- **constraints** (optional): List of constraints (e.g., "Use PostgreSQL", "No external APIs")
- **deliverables** (optional): Expected outputs (e.g., "API endpoints", "Unit tests")

## Steps
1. **Harvest Context**: Scan repo for package.json, configs, scripts, tests.
2. **Classify Task**: Determine role (engineer/pm/research).
3. **Generate Candidates**: Use VS to propose k designs with probabilities.
4. **Run Checks**: Verify security, correctness, style, perf, testability.
5. **Select Winner**: Pick highest-scoring candidate.
6. **Self-Adapt**: Generate Self-Edits and persist to \`skills/self-edits.json\`.
7. **Emit Prompt**: Return Cursor-native instruction (plan-first, diff-oriented, explicit paths).

## Output
A JSON response with:
- \`system\`: Role description
- \`instructions\`: Full prompt text
- \`context_snippets\`: Relevant code examples
- \`plan\`: Step-by-step execution plan
- \`checks\`: Acceptance criteria
- \`deliverables\`: Expected outputs
- \`vs_candidates\`: (if enabled) List of designs with probabilities
- \`selected_candidate\`: (if enabled) ID of winner
- \`self_edits\`: (if enabled) New improvement rules

## Example
\`\`\`bash
curl -X POST http://localhost:3000/rewrite \\
  -H "Content-Type: application/json" \\
  -d '{
    "task": "Add dark mode toggle to settings",
    "mode_flags": { "vs_enabled": true, "vs_k": 3, "self_adapt": true },
    "constraints": ["Use CSS variables", "Persist preference in localStorage"],
    "deliverables": ["Toggle component", "Unit tests", "E2E test"]
  }'
\`\`\`

---
Generated by Prompt Orchestrator (Cursor MVP)
`;
}


